site_name: "MEDUtils"
repo_url: https://github.com/malcolm-3/medutils

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: 'index.md'
  - api_docs.md
  - changelog.md

watch:
  - src/medutils
  
markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - table-reader
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
	  paths: [src]
	  optoins:
            show_signature_annotations: true
            show_submodules: true

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
